### PR TITLE
fix(transformer): Small transformer improvement

### PR DESCRIPTION
**Pull request by achedeuzot**

### CODE REVIEW

**Comment by abusi** [comment]
You can rebase it ;)

**Comment by achedeuzot** [comment]
It's rebased now 👍

**Comment by achedeuzot** [comment]
It's rebased now 👍

**Comment by achedeuzot** [comment]
Could you reapply my change in one of your commits ? 
I can't merge so the previous change was OK and you never merged it and now I have to rebase again :/

**Comment by abusi** [comment]
oh, yeah, i'll do it and merge it @achedeuzot, thanks :)

**Pull request closed without merging**
